### ISSUE TITLE
Cannot access API locally using Docker

### ISSUE THREAD

**Issue by stephenshank** [hivdb/sierra#27]
Dear Sierra developers,

First, thanks for your work on this awesome project. I am trying to run a local Sierra instance in order to query drug resistance scores for sequences that must remain private. In short, I was able to execute the query for the database version, but not for the [sequence analysis example](https://hivdb.stanford.edu/page/graphiql/?example=sequenceAnalysis).

The Docker startup command on `README.md` did not work for me (connection refused), but a slight modification did (mapping container port to local port):

```
docker run -it -p 8080:8080 hivdb/sierra dev
```

Running in this manner, I was able to query for the version as in the [minimal working example](https://hivdb.stanford.edu/page/webservice/#minimal.working.examples).

However, I am unable to execute the sequence analysis query. I've captured the HTTP request made from the [GraphiQL interface](https://hivdb.stanford.edu/page/graphiql/) to ensure that I was making a valid submission to the Sierra API, using [Postman](https://www.postman.com/). I submit an identical JSON Body to http://localhost:8080/WebApplications/rest/graphql, and receive the following error:

```
  "errors": [
    {
      "type": "DataFetchingException",
      "message": "Exception while fetching data (/sequenceAnalysis) : null",
```

This same request, when made to https://hivdb.stanford.edu/graphql, returns the desired result. The version query made to this URL also works. I've attached the full JSON error in case it helps.

I hope what I've written makes sense; any assistance you can provide in getting this query working would be greatly appreciated. Thanks in advance for your response!

Best,
Stephen

[error.txt](https://github.com/hivdb/sierra/files/4653822/error.txt)

**Comment by philiptzou** [comment]
Hi Stephen, thanks for pointing out the problem in the docker command. I have updated our README.md file.

Can you run this command and let me know what the output is?

```
docker images | grep sierra
```

**Comment by stephenshank** [comment]
Hello @philiptzou,

Thanks for the prompt response! Upon running that command, I obtain:

```
hivdb/sierra        latest              10df5364d66a        7 days ago          816MB
```

Best,
Stephen

**Comment by philiptzou** [comment]
It might be a local NucAmino runner issue. I'll check it soon.

**Comment by philiptzou** [comment]
@stephenshank I have fixed this problem. It turns out the version of nucamino included in our Docker image is too old.

Please use this command to pull the latest version and you should be able to use Sierra locally.

```bash
docker pull hivdb/sierra:latest
```

**Comment by stephenshank** [comment]
Dear @philiptzou,

That worked! Thank you so much, I really appreciate the effort.

Best,
Stephen
