### ISSUE TITLE
URL

### ISSUE THREAD

**Issue by lwxing** [hivdb/sierra#29]
**issue** : I've started the mirror,but the local Sierra web service is not accessable through this URL:http://localhost:8080/WebApplications/rest/graphql

itcast@ubuntu:~$ sudo docker run -it --publish=8080:8080 hivdb/sierra dev
Using CATALINA_BASE:   /usr/share/tomcat
Using CATALINA_HOME:   /usr/share/tomcat
Using CATALINA_TMPDIR: /usr/share/tomcat/temp
Using JRE_HOME:        /usr
Using CLASSPATH:       /usr/share/tomcat/bin/bootstrap.jar:/usr/share/tomcat/bin/tomcat-juli.jar
NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
09-Dec-2020 01:08:53.902 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/9.0.35
09-Dec-2020 01:08:53.910 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          May 5 2020 20:36:20 UTC
09-Dec-2020 01:08:53.910 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 9.0.35.0
09-Dec-2020 01:08:53.910 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
09-Dec-2020 01:08:53.911 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            5.4.0-56-generic
09-Dec-2020 01:08:53.911 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
09-Dec-2020 01:08:53.911 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-14-oracle
09-Dec-2020 01:08:53.912 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           14.0.1+7
09-Dec-2020 01:08:53.917 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
09-Dec-2020 01:08:53.917 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/share/tomcat9/apache-tomcat-9.0.35
09-Dec-2020 01:08:53.917 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/share/tomcat9/apache-tomcat-9.0.35
09-Dec-2020 01:08:53.962 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED
09-Dec-2020 01:08:53.963 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.io=ALL-UNNAMED
09-Dec-2020 01:08:53.963 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
09-Dec-2020 01:08:53.963 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/share/tomcat/conf/logging.properties
09-Dec-2020 01:08:53.964 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
09-Dec-2020 01:08:53.964 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
09-Dec-2020 01:08:53.965 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
09-Dec-2020 01:08:53.966 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
09-Dec-2020 01:08:53.967 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xms512M
09-Dec-2020 01:08:53.967 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xmx1024M
09-Dec-2020 01:08:53.967 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
09-Dec-2020 01:08:53.968 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/share/tomcat
09-Dec-2020 01:08:53.971 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/share/tomcat
09-Dec-2020 01:08:53.972 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/share/tomcat/temp
09-Dec-2020 01:08:53.972 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The Apache Tomcat Native library which allows using OpenSSL was not found on the java.library.path: [/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib]
09-Dec-2020 01:08:54.597 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
09-Dec-2020 01:08:54.677 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [1,131] milliseconds
09-Dec-2020 01:08:54.762 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
09-Dec-2020 01:08:54.763 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/9.0.35]
09-Dec-2020 01:08:54.788 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/usr/share/tomcat9/apache-tomcat-9.0.35/webapps/WebApplications.war]
09-Dec-2020 01:08:57.731 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
09-Dec-2020 01:09:02.173 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/share/tomcat9/apache-tomcat-9.0.35/webapps/WebApplications.war] has finished in [7,384] ms
09-Dec-2020 01:09:02.183 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
09-Dec-2020 01:09:02.223 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [7,545] milliseconds

**Comment by philiptzou** [comment]
@lwxing It looks like the service started properly. However, the graphql API endpoint only accept POST method. Did you try to access it in browser? The API is by design not directly accessible from a browser unless using JavaScript.

The frontend part of our website is not open source. However, you can use [`sierrapy`](https://github.com/hivdb/sierra-client/tree/master/python) to run analysis by pointing the `--url` parameter to the localhost address. Hope this is helpful.

**Comment by lwxing** [comment]
@philiptzou
It worked.  Thank you very much .
