### ISSUE TITLE
Graphql, adjustedAlignedAAs, Invalid targetStrain #5

### ISSUE THREAD

**Issue by KaimingTao** [hivdb/sierra#31]
"type": "DataFetchingException",
"message": "Exception while fetching data (/sequenceAnalysis[0]/alignedGeneSequences[0]/adjustedAlignedAAs) : Strain modifier for target strain HI is not defined",

**Comment by philiptzou** [comment]
@KaimingTao It looks like the target strain you put in was "HI".

**Comment by KaimingTao** [comment]
This issue is too old and lost the context, Iw will close it.
